apiVersion: v1
kind: ServiceAccount
metadata:
  name: web-cms-strapi-hook-proxy-sa-sandbox2
  namespace: web-cms-strapi-hook-proxy-sandbox2
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: web-cms-strapi-hook-proxy-role-sandbox2
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: web-cms-strapi-hook-proxy-rolebinding-sandbox2
  namespace: web-aoc-sandbox2
subjects:
- kind: ServiceAccount
  name: web-cms-strapi-hook-proxy-sa-sandbox2
  namespace: web-cms-strapi-hook-proxy-sandbox2
roleRef:
  kind: ClusterRole
  name: web-cms-strapi-hook-proxy-role-sandbox2
  apiGroup: rbac.authorization.k8s.io