apiVersion: v1
kind: ServiceAccount
metadata:
  name: web-cms-strapi-hook-proxy-sa-prod
  namespace: web-cms-strapi-hook-proxy-prod
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: web-cms-strapi-hook-proxy-role-prod
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: web-cms-strapi-hook-proxy-rolebinding-prod
  namespace: web-aoc-prod
subjects:
- kind: ServiceAccount
  name: web-cms-strapi-hook-proxy-sa-prod
  namespace: web-cms-strapi-hook-proxy-prod
roleRef:
  kind: ClusterRole
  name: web-cms-strapi-hook-proxy-role-prod
  apiGroup: rbac.authorization.k8s.io