apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-cms-strapi-hook-proxy-staging
  namespace: web-cms-strapi-hook-proxy-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-cms-strapi-hook-proxy-staging
  template:
    metadata:
      labels:
        app: web-cms-strapi-hook-proxy-staging
    spec:
      serviceAccountName: web-cms-strapi-hook-proxy-sa-staging
      containers:
      - name: web-cms-strapi-hook-proxy-staging
        image: 524500438133.dkr.ecr.us-west-2.amazonaws.com/web-cms-strapi-hook-proxy:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 3000