apiVersion: v1
kind: ServiceAccount
metadata:
  name: web-cms-strapi-hook-proxy-sa-staging
  namespace: web-cms-strapi-hook-proxy-staging
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: web-cms-strapi-hook-proxy-role-staging
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: web-cms-strapi-hook-proxy-rolebinding-staging
  namespace: web-aoc-staging
subjects:
- kind: ServiceAccount
  name: web-cms-strapi-hook-proxy-sa-staging
  namespace: web-cms-strapi-hook-proxy-staging
roleRef:
  kind: ClusterRole
  name: web-cms-strapi-hook-proxy-role-staging
  apiGroup: rbac.authorization.k8s.io