apiVersion: v1
kind: Service
metadata:
  name: web-cms-strapi-hook-proxy-stage
  namespace: web-cms-strapi-hook-proxy-stage
spec:
  selector:
    app: web-cms-strapi-hook-proxy-stage
  ports:
    - name: http
      port: 3000